---
- include: load-variables.yml

- include: "setup-RedHat-family-prerequisites.yml"
  when: ansible_os_family == 'RedHat'

- include: setup-Debian-family-prerequisites.yml
  when: ansible_os_family == 'Debian'
  
# tasks file for mod gearman worker
- include: setup-thruk.yml

- name: Ensure Apache has selected state and enabled on boot.
  service:
    name: "{{ apache_service }}"
    state: "{{ apache_state }}"
    enabled: "{{ apache_enabled }}"
