---

- name: Install  dependencies (Debian).
  package:
    name:
      - gnupg2 
    state: latest
    
- name: Add labs.consol Key
  apt_key:
    url: "https://labs.consol.de/repo/stable/RPM-GPG-KEY"
    state: present

- name: Add labs.consol Repository
  apt_repository:
    repo: "deb http://labs.consol.de/repo/stable/debian {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes
 
- name: Wait for cloud-init
  command: /usr/bin/cloud-init status --wait
   
- name: Wait 2 minutes for APT to complete on AWS instances
  pause:
    minutes: 2