---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  vars:
    expected_content: "Thruk Monitoring Webinterface"
  tasks:
    - name: Get index.html
      uri:
        url: http://localhost/thruk/cgi-bin/login.cgi?thruk/
        return_content: yes
      register: this
      failed_when: "expected_content not in this.content"

    - name: Ensure content type is text/html
      assert:
        that:
          - "'text/html' in this.content_type"
